import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('开始导入种子数据...');

  // 导入产品数据
  const products = [
    {
      id: 'tp-1',
      name: '涤纶三防面料',
      description: '高强度涤纶，耐磨防水',
      price: 45.00,
      category: '三防面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 1,
    },
    {
      id: 'tp-2',
      name: '尼龙三防面料',
      description: '轻盈柔软，强力防水',
      price: 55.00,
      category: '三防面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 2,
    },
    {
      id: 'tp-3',
      name: '棉质三防面料',
      description: '天然舒适，三防处理',
      price: 65.00,
      category: '三防面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 3,
    },
    {
      id: 'tp-4',
      name: '复合三防面料',
      description: '多层复合，功能全面',
      price: 85.00,
      category: '三防面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 4,
    },
    {
      id: 'aa-1',
      name: '涤纶防酸碱面料',
      description: '化学稳定性好',
      price: 75.00,
      category: '防酸碱面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 1,
    },
    {
      id: 'aa-2',
      name: 'PVC涂层防酸碱',
      description: '完全密封防护',
      price: 95.00,
      category: '防酸碱面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 2,
    },
    {
      id: 'aa-3',
      name: '橡胶防酸碱面料',
      description: '弹性好耐腐蚀',
      price: 115.00,
      category: '防酸碱面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 3,
    },
    {
      id: 'aa-4',
      name: '复合防酸碱面料',
      description: '多层复合结构',
      price: 135.00,
      category: '防酸碱面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 4,
    },
    {
      id: 'as-1',
      name: '涤纶防静电面料',
      description: '导电丝编织',
      price: 55.00,
      category: '防静电面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 1,
    },
    {
      id: 'as-2',
      name: '棉质防静电面料',
      description: '舒适抗静电',
      price: 65.00,
      category: '防静电面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 2,
    },
    {
      id: 'as-3',
      name: '网格防静电面料',
      description: '网格导电设计',
      price: 75.00,
      category: '防静电面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 3,
    },
    {
      id: 'as-4',
      name: '条纹防静电面料',
      description: '条纹导电丝',
      price: 85.00,
      category: '防静电面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 4,
    },
    {
      id: 'med-1',
      name: '涤棉医护面料',
      description: '舒适耐用',
      price: 35.00,
      category: '医护面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 1,
    },
    {
      id: 'med-2',
      name: '全棉医护面料',
      description: '天然亲肤',
      price: 45.00,
      category: '医护面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 2,
    },
    {
      id: 'med-3',
      name: '抗菌医护面料',
      description: '银离子抗菌',
      price: 65.00,
      category: '医护面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 3,
    },
    {
      id: 'med-4',
      name: '手术服面料',
      description: '高阻隔性',
      price: 85.00,
      category: '医护面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 4,
    },
    {
      id: 'pc-1',
      name: 'T/C 65/35面料',
      description: '标准工装面料',
      price: 25.00,
      category: '涤棉面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 1,
    },
    {
      id: 'pc-2',
      name: 'T/C 80/20面料',
      description: '高涤含量',
      price: 28.00,
      category: '涤棉面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 2,
    },
    {
      id: 'pc-3',
      name: 'CVC 60/40面料',
      description: '棉含量高',
      price: 32.00,
      category: '涤棉面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 3,
    },
    {
      id: 'pc-4',
      name: '涤棉斜纹面料',
      description: '经典斜纹',
      price: 35.00,
      category: '涤棉面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 4,
    },
    {
      id: 'el-1',
      name: '涤纶弹力面料',
      description: '四面弹力',
      price: 45.00,
      category: '弹力面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 1,
    },
    {
      id: 'el-2',
      name: '尼龙弹力面料',
      description: '高弹耐磨',
      price: 55.00,
      category: '弹力面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 2,
    },
    {
      id: 'el-3',
      name: '棉质弹力面料',
      description: '舒适弹力',
      price: 65.00,
      category: '弹力面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 3,
    },
    {
      id: 'el-4',
      name: '弹力斜纹面料',
      description: '工装弹力',
      price: 75.00,
      category: '弹力面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 4,
    },
    {
      id: 'fl-1',
      name: '荧光黄面料',
      description: '高亮黄色',
      price: 55.00,
      category: '荧光面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 1,
    },
    {
      id: 'fl-2',
      name: '荧光橙面料',
      description: '警示橙色',
      price: 55.00,
      category: '荧光面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 2,
    },
    {
      id: 'fl-3',
      name: '反光条面料',
      description: '带反光条',
      price: 75.00,
      category: '荧光面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 3,
    },
    {
      id: 'fl-4',
      name: '荧光涤棉面料',
      description: '舒适荧光',
      price: 65.00,
      category: '荧光面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 4,
    },
    {
      id: 'pr-1',
      name: '迷彩印花面料',
      description: '军用迷彩',
      price: 65.00,
      category: '印花面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 1,
    },
    {
      id: 'pr-2',
      name: '数码印花面料',
      description: '高清数码',
      price: 85.00,
      category: '印花面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 2,
    },
    {
      id: 'pr-3',
      name: '圆网印花面料',
      description: '大批量印花',
      price: 55.00,
      category: '印花面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 3,
    },
    {
      id: 'pr-4',
      name: '转移印花面料',
      description: '精细图案',
      price: 75.00,
      category: '印花面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 4,
    },
    {
      id: 'ln-1',
      name: '纯亚麻面料',
      description: '100%天然亚麻',
      price: 95.00,
      category: '亚麻面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 1,
    },
    {
      id: 'ln-2',
      name: '亚麻棉混纺',
      description: '柔软舒适',
      price: 75.00,
      category: '亚麻面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 2,
    },
    {
      id: 'ln-3',
      name: '亚麻粘胶',
      description: '光泽度好',
      price: 85.00,
      category: '亚麻面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 3,
    },
    {
      id: 'ln-4',
      name: '雨露麻面料',
      description: '高品质亚麻',
      price: 115.00,
      category: '亚麻面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 4,
    },
    {
      id: 'wl-1',
      name: '精纺羊毛面料',
      description: '细腻光滑',
      price: 185.00,
      category: '羊毛面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 1,
    },
    {
      id: 'wl-2',
      name: '粗纺羊毛面料',
      description: '厚实保暖',
      price: 165.00,
      category: '羊毛面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 2,
    },
    {
      id: 'wl-3',
      name: '羊毛涤纶混纺',
      description: '易打理',
      price: 145.00,
      category: '羊毛面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 3,
    },
    {
      id: 'wl-4',
      name: '羊绒面料',
      description: '奢华柔软',
      price: 285.00,
      category: '羊毛面料',
      images: ['https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400'],
      isActive: true,
      sortOrder: 4,
    },
  ];

  // 导入新闻数据
  const news = [
    {
      id: 'news-1',
      title: '天睿纺织荣获2024年度优秀出口企业称号',
      summary: '凭借卓越的产品质量和优质的客户服务，天睿纺织在国际市场上获得广泛认可...',
      coverImage: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=400&h=250&fit=crop',
      author: '天睿纺织',
      category: '企业新闻',
      isPublished: true,
      publishedAt: new Date('2024-12-15'),
      viewCount: 128,
    },
    {
      id: 'news-2',
      title: '新型防火面料技术突破，通过国际权威认证',
      summary: '公司研发团队成功开发出新一代高性能防火面料，已通过欧盟CE认证...',
      coverImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=250&fit=crop',
      author: '研发中心',
      category: '技术创新',
      isPublished: true,
      publishedAt: new Date('2024-11-28'),
      viewCount: 256,
    },
    {
      id: 'news-3',
      title: '天睿纺织参加德国慕尼黑功能性面料展览会',
      summary: '作为亚洲领先的功能性面料供应商，天睿纺织携最新产品亮相国际展会...',
      coverImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=250&fit=crop',
      author: '市场部',
      category: '展会动态',
      isPublished: true,
      publishedAt: new Date('2024-10-20'),
      viewCount: 189,
    },
  ];

  // 清空现有数据
  console.log('清空现有数据...');
  await prisma.product.deleteMany();
  await prisma.news.deleteMany();

  // 插入产品数据
  console.log('导入产品数据...');
  for (const product of products) {
    await prisma.product.create({
      data: {
        id: product.id,
        name: product.name,
        description: product.description,
        price: product.price,
        category: product.category,
        images: product.images,
        isActive: product.isActive,
        sortOrder: product.sortOrder,
      },
    });
  }
  console.log(`已导入 ${products.length} 个产品`);

  // 插入新闻数据
  console.log('导入新闻数据...');
  for (const item of news) {
    await prisma.news.create({
      data: {
        id: item.id,
        title: item.title,
        summary: item.summary,
        coverImage: item.coverImage,
        author: item.author,
        category: item.category,
        isPublished: item.isPublished,
        publishedAt: item.publishedAt,
        viewCount: item.viewCount,
      },
    });
  }
  console.log(`已导入 ${news.length} 条新闻`);

  console.log('种子数据导入完成！');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
