import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  zh: {
    'nav.home': '天睿首页',
    'nav.news': '新闻资讯',
    'nav.about': '走进天睿',
    'nav.products': '天睿产品',
    'nav.honors': '资质荣誉',
    'nav.factory': '厂区厂貌',
    'nav.message': '在线留言',
    'nav.contact': '联系我们',
    'hero.title': '航行全球的功能性面料专家',
    'hero.subtitle': '从研发到出口，一站式定制化解决方案',
    'hero.brandTag': '天睿纺织 · 专业防护面料',
    'hero.companyName': '新乡市天睿纺织印染有限公司',
    'hero.companyDesc': '公司专注于生产销售工装面料，制服面料以及功能性面料，于2022年完成从纺纱，织布，印染，到后整理一体的全产业链面料供应商的蜕变',
    'hero.cta.learnMore': '走进天睿',
    'hero.cta.sample': '获取样品',
    'hero.cta.contact': '联系销售',
    'home.advantages.title': '专注防护 合作无忧',
    'home.advantages.subtitle': '让我们为您的安全保驾护航',
    'home.advantages.strength.title': '实力雄厚',
    'home.advantages.strength.desc': '拥有纺纱30000锭，喷气织机416台，染色线4条，印花线1条；专家级总工4人，10年以上相关领域工作经验的技术人员10人',
    'home.advantages.technology.title': '技术夯实',
    'home.advantages.technology.desc': '已经通过ISO9001，ISO14001等管理体系认证，OEKO-TEX 100认证，GRS认证，OCS认证，UL认证，以及产品可以通过SGS，BTTG，ITS等检测',
    'home.advantage.iso': 'ISO认证',
    'home.advantage.iso.desc': 'ISO9001质量管理体系认证',
    'home.advantage.sampling': '快速打样',
    'home.advantage.sampling.desc': '7天内完成样品制作',
    'home.advantage.experience': '20年经验',
    'home.advantage.experience.desc': '深耕功能性面料行业',
    'home.advantage.global': '全球认证',
    'home.advantage.global.desc': 'OEKO-TEX、REACH等认证',
    'home.products.subtitle': '11大面料材质系列，满足各行业专业需求',
    'home.products.viewAll': '查看全部',
    'home.products.viewAllDesc': '浏览所有产品系列',
    'home.fabric.aramid': '芳纶',
    'home.fabric.finishedFR': '后整理阻燃',
    'home.fabric.waterproof': '防水面料',
    'home.fabric.oilproof': '防油面料',
    'home.fabric.stainresistant': '易去污面料',
    'home.fabric.t400': 'T400面料',
    'home.fabric.spandex': '氨纶面料',
    'home.fabric.flameretardant': '阻燃面料',
    'home.fabric.flameretardant.desc': '采用先进阻燃技术，符合EN11612标准',
    'home.fabric.threeproof': '三防面料',
    'home.fabric.threeproof.desc': '防水防油防污三合一功能',
    'home.fabric.acidalkali': '防酸碱面料',
    'home.fabric.acidalkali.desc': '专业防化学腐蚀面料',
    'home.fabric.antistatic': '防静电面料',
    'home.fabric.antistatic.desc': '永久性抗静电处理',
    'home.fabric.medical': '医护面料',
    'home.fabric.medical.desc': '抗菌防液体渗透',
    'home.fabric.polycotton': '涤棉面料',
    'home.fabric.polycotton.desc': '涤棉混纺，性价比高',
    'home.fabric.elastic': '弹力面料',
    'home.fabric.elastic.desc': '高弹性回复性好',
    'home.fabric.fluorescent': '荧光面料',
    'home.fabric.fluorescent.desc': '高可视性安全警示',
    'home.fabric.printed': '印花面料',
    'home.fabric.printed.desc': '图案清晰色彩鲜艳',
    'home.fabric.linen': '亚麻面料',
    'home.fabric.linen.desc': '天然纤维吸湿透气',
    'home.fabric.wool': '羊毛面料',
    'home.fabric.wool.desc': '保暖性极佳手感柔软',
    'home.news.1.title': '天睿纺织参加2024中国国际纺织面料博览会',
    'home.news.1.summary': '展示最新功能性面料产品',
    'home.news.2.title': '公司荣获省级高新技术企业认定',
    'home.news.2.summary': '技术创新能力获认可',
    'home.news.3.title': '新型环保防水面料研发成功',
    'home.news.3.summary': '采用可降解材料，绿色环保',
    'about.intro': '专注功能性面料13年',
    'about.profileTitle': '公司简介',
    'about.companyDesc': '新乡市天睿纺织印染有限公司成立于2013年专注于生产销售工装面料，制服面料以及功能性面料。公司历经10年，已经于2022年完成从纺纱，织布，印染，到后整理一体的全产业链面料供应商的蜕变，公司拥有纺纱110000锭，喷气织机416台，染色线4条，印花线1条。产品覆盖TC，CVC，全棉,TR，全涤，棉锦等；功能性面料包括：阻燃，抗油拒水，防静电，防酸碱，易去污，特氟龙，防紫外线，防辐射等，涵盖了消防，石油，化工等多个行业领域。公司已经通过ISO9001，ISO14001等管理体系认证，OEKO-TEX 100认证，GRS认证，OCS认证，UL认证，以及产品可以通过SGS，BTTG，ITS等三方检测机构的检测。公司的拥有一支经验丰富的团队，专家级总工4人，30年以上相关领域工作经验的技术人员10人。',
    'about.companyPhilosophy': '我们始终坚持"质量第一、客户至上"的经营理念，致力于为客户提供最优质的产品和服务。',
    'about.yearsExp': '年行业经验',
    'about.exportCountries': '出口国家',
    'about.globalClients': '全球客户',
    'about.patents': '专利技术',
    'about.milestones': '发展历程',
    'about.culture': '企业文化',
    'about.team': '核心团队',
    'about.readMore': '阅读更多',
    'about.milestone.2013': '公司成立',
    'about.milestone.2014': 'ISO9001认证',
    'about.milestone.2018': '出口突破100国',
    'about.milestone.2020': '新厂区投产',
    'about.milestone.2026': '行业领军品牌',
    'about.value.innovation': '创新',
    'about.value.innovation.desc': '持续研发新技术',
    'about.value.quality': '品质',
    'about.value.quality.desc': '严格质量管控',
    'about.value.integrity': '诚信',
    'about.value.integrity.desc': '真诚服务客户',
    'about.value.winwin': '共赢',
    'about.value.winwin.desc': '携手共创未来',
    'about.team.founder': '创始人/CEO',
    'about.team.founder.en': 'Founder/CEO',
    'about.team.cto': '技术总监',
    'about.team.cto.en': 'CTO',
    'about.team.sales': '销售总监',
    'about.team.sales.en': 'Sales Director',
    'about.team.production': '生产总监',
    'about.team.production.en': 'Production Director',
    'honors.subtitle': '天睿纺织始终坚持品质至上，获得多项国际权威认证与荣誉资质',
    'honors.iso9001': 'ISO 9001质量管理体系认证',
    'honors.iso14001': 'ISO 14001环境管理体系认证',
    'honors.oekotex': 'OEKO-TEX Standard 100认证',
    'honors.hightech': '国家高新技术企业',
    'honors.ce': '欧盟CE认证',
    'honors.ul': '美国UL认证',
    'honors.textileaward': '中国纺织工业联合会科技进步奖',
    'honors.famoustrademark': '江苏省著名商标',
    'factory.equipment': '生产设备',
    'factory.productionLines': '生产线展示',
    'factory.intelligentLine': '智能化生产线',
    'factory.environment': '环境展示',
    'contact.info': '联系方式',
    'contact.address': '地址',
    'contact.phone': '电话',
    'contact.email': '邮箱',
    'contact.workingHours': '工作时间',
    'contact.quickContact': '快速联系',
    'contact.workTime': '周一至周五 8:30-17:30',
    'inquiry.selectProduct': '请选择产品',
    'inquiry.productPlaceholder': '请输入产品名称（如：阻燃工装面料、防水透气面料等）',
    'inquiry.quantityPlaceholder': '例如：1000米',
    'inquiry.submitted': '询盘提交成功！',
    'productDetail.notFound': '产品未找到',
    'productDetail.backToProducts': '返回产品列表',
    'productDetail.specs': '产品参数',
    'productDetail.relatedProducts': '相关产品',
    'productDetail.flameRetardant': '阻燃',
    'news.readMore': '阅读更多',
    'advantages.title': '核心优势',
    'advantages.iso': 'ISO认证',
    'advantages.sample': '快速打样',
    'advantages.experience': '20年行业经验',
    'advantages.global': '全球资质认证',
    'products.title': '产品系列',
    'products.subtitle': '按面料材质分类，11大系列专业功能性面料，满足各行业需求',
    'products.viewDetails': '查看详情',
    'products.inquiryNow': '立即询盘',
    'products.download': '下载样本',
    'products.productCount': '款产品',
    'products.features': '产品特点',
    'products.specifications': '技术参数',
    'products.applications': '应用领域',
    'factory.title': '新乡天睿 厂区厂貌',
    'factory.subtitle': '先进的生产设备与严格的质量管理体系',
    'news.title': '最新资讯',
    'partners.title': '合作伙伴',
    'footer.address': '地址：中国江苏省苏州市工业园区',
    'footer.phone': '电话：+86 512-8888-8888',
    'footer.email': '邮箱：info@tianrui-textile.com',
    'inquiry.title': '欢迎询盘',
    'inquiry.name': '您的姓名',
    'inquiry.company': '公司名称',
    'inquiry.email': '电子邮箱',
    'inquiry.phone': '联系电话',
    'inquiry.product': '感兴趣的产品',
    'inquiry.quantity': '预计数量',
    'inquiry.message': '留言内容',
    'inquiry.submit': '提交询盘',
    'inquiry.submitting': '提交中...',
    'message.submitted': '留言提交成功，我们会尽快与您联系！',
    'message.submitting': '提交中...',
    'message.error.nameRequired': '请输入姓名',
    'message.error.emailRequired': '请输入邮箱',
    'message.error.emailInvalid': '邮箱格式不正确',
    'message.error.messageRequired': '请输入留言内容',
    'message.placeholder.name': '请输入您的姓名',
    'message.placeholder.company': '请输入公司名称',
    'message.placeholder.email': '请输入电子邮箱',
    'message.placeholder.phone': '请输入联系电话',
    'message.placeholder.message': '请输入您的留言内容',
    'factory.capacity': '年产能力：5000万米',
    'factory.automation': '自动化率：95%',
    'factory.passRate': '良品率：99.5%',
    'chat.title': '在线客服',
    'chat.placeholder': '请输入您的问题...',
    'chat.send': '发送',
    // VideoHero
    'videoHero.brandTag': '天睿纺织 · 专业防护面料',
    'videoHero.mainTitle': '[天睿] 织造未来',
    'videoHero.subtitle': 'Weaving the Future',
    'videoHero.description': '专注功能性面料研发与生产，为全球客户提供高品质纺织解决方案',
    'videoHero.cta.products': '探索产品',
    'videoHero.cta.factory': '了解工厂',
    'videoHero.companyName': '天睿纺织',
    // DynamicBanner
    'dynamicBanner.brandTag': '天睿纺织 · 专业防护面料',
    'dynamicBanner.paramsLabel': '防护性能参数',
    'dynamicBanner.cta.learnMore': '了解更多',
    'dynamicBanner.scene.firefighter.title': '消防作业服',
    'dynamicBanner.scene.firefighter.subtitle': '阻燃隔热 · 守护生命安全',
    'dynamicBanner.scene.firefighter.desc': '采用芳纶纤维与阻燃整理技术，具备优异的阻燃性能和热防护性能，为消防员提供全方位安全保障',
    'dynamicBanner.scene.oil.title': '石油作业服',
    'dynamicBanner.scene.oil.subtitle': '防静电阻燃 · 工业安全首选',
    'dynamicBanner.scene.oil.desc': '专为石油天然气行业设计，兼具防静电、阻燃、防油多重功能，适应海上平台及陆地油田恶劣环境',
    'dynamicBanner.scene.chemical.title': '化工作业服',
    'dynamicBanner.scene.chemical.subtitle': '防酸碱腐蚀 · 专业化学防护',
    'dynamicBanner.scene.chemical.desc': '采用多层复合防护技术，有效阻隔各类化学液体渗透，为化工生产人员提供可靠的化学防护屏障',
    'dynamicBanner.scene.medical.title': '医护作业服',
    'dynamicBanner.scene.medical.subtitle': '抗菌防渗透 · 医疗级防护',
    'dynamicBanner.scene.medical.desc': '医疗级功能性面料，具备抗菌、防液体渗透、透气舒适等特性，满足手术室及病房专业防护需求',
    // FactoryShowcase
    'factoryShowcase.sectionTitle': '厂区厂貌',
    'factoryShowcase.sectionSubtitle': '现代化智能工厂，从纺纱到印染的全产业链布局',
    'factoryShowcase.scene.panorama.title': '厂区全景',
    'factoryShowcase.scene.panorama.titleEn': 'Factory Panorama',
    'factoryShowcase.scene.panorama.desc': '现代化工业园区，集研发、生产、仓储于一体',
    'factoryShowcase.scene.weaving.title': '织布车间',
    'factoryShowcase.scene.weaving.titleEn': 'Weaving Workshop',
    'factoryShowcase.scene.weaving.desc': '国际先进喷气织机，高效精密织造各类功能性面料',
    'factoryShowcase.scene.spinning.title': '纺纱车间',
    'factoryShowcase.scene.spinning.titleEn': 'Spinning Mill',
    'factoryShowcase.scene.spinning.desc': '智能化纺纱生产线，从源头把控纱线品质',
    'factoryShowcase.scene.dyeing.title': '印染车间',
    'factoryShowcase.scene.dyeing.titleEn': 'Dyeing & Printing',
    'factoryShowcase.scene.dyeing.desc': '环保印染工艺，色彩精准，牢度优异',
    'factoryShowcase.stat.area': '占地面积',
    'factoryShowcase.stat.buildingArea': '建筑面积',
    'factoryShowcase.stat.greenRate': '绿化率',
    'factoryShowcase.stat.looms': '喷气织机',
    'factoryShowcase.stat.capacity': '年产能',
    'factoryShowcase.stat.automation': '自动化率',
    'factoryShowcase.stat.spindles': '纺纱锭数',
    'factoryShowcase.stat.dailyOutput': '日产量',
    'factoryShowcase.stat.varieties': '纱线品种',
    'factoryShowcase.stat.dyeingLines': '染色生产线',
    'factoryShowcase.stat.printingLines': '印花生产线',
    'factoryShowcase.stat.processingCapacity': '日处理量',
    'factoryShowcase.footer.capacity': '年产能力：5000万米',
    'factoryShowcase.footer.automation': '自动化率：95%',
    'factoryShowcase.footer.passRate': '良品率：99.5%',
  },
  en: {
    'nav.home': 'Home',
    'nav.news': 'News',
    'nav.about': 'About Us',
    'nav.products': 'Products',
    'nav.honors': 'Honors',
    'nav.factory': 'Factory',
    'nav.message': 'Message',
    'nav.contact': 'Contact',
    'hero.title': 'Global Functional Fabric Expert',
    'hero.subtitle': 'One-Stop Customized Solution from R&D to Export',
    'hero.brandTag': 'Tianrui Textile · Professional Protective Fabrics',
    'hero.companyName': 'Xinxiang Tianrui Textile & Dyeing Co., Ltd.',
    'hero.companyDesc': 'The company focuses on the production and sales of workwear fabrics, uniform fabrics and functional fabrics. In 2022, it completed the transformation into a full industrial chain fabric supplier integrating spinning, weaving, dyeing and finishing.',
    'hero.cta.learnMore': 'Learn More',
    'hero.cta.sample': 'Get Samples',
    'hero.cta.contact': 'Contact Sales',
    'home.advantages.title': 'Focus on Protection, Worry-free Cooperation',
    'home.advantages.subtitle': 'Let us safeguard your safety',
    'home.advantages.strength.title': 'Strong Strength',
    'home.advantages.strength.desc': '30,000 spinning spindles, 416 air-jet looms, 4 dyeing lines, 1 printing line; 4 expert-level chief engineers, 10 technical personnel with over 10 years of experience',
    'home.advantages.technology.title': 'Solid Technology',
    'home.advantages.technology.desc': 'Passed ISO9001, ISO14001 management system certifications, OEKO-TEX 100, GRS, OCS, UL certifications, and products can be tested by SGS, BTTG, ITS',
    'home.advantage.iso': 'ISO Certified',
    'home.advantage.iso.desc': 'ISO9001 Quality Management System',
    'home.advantage.sampling': 'Fast Sampling',
    'home.advantage.sampling.desc': 'Complete sampling within 7 days',
    'home.advantage.experience': '20 Years Experience',
    'home.advantage.experience.desc': 'Deep expertise in functional fabrics industry',
    'home.advantage.global': 'Global Certifications',
    'home.advantage.global.desc': 'OEKO-TEX, REACH and other certifications',
    'home.products.subtitle': '11 Fabric Material Series for Professional Needs',
    'home.products.viewAll': 'View All',
    'home.products.viewAllDesc': 'Browse all product series',
    'home.fabric.aramid': 'Aramid',
    'home.fabric.finishedFR': 'Finished FR',
    'home.fabric.waterproof': 'Waterproof Fabric',
    'home.fabric.oilproof': 'Oil Resistant Fabric',
    'home.fabric.stainresistant': 'Stain Resistant Fabric',
    'home.fabric.t400': 'T400 Fabric',
    'home.fabric.spandex': 'Spandex Fabric',
    'home.fabric.flameretardant': 'Flame Retardant Fabric',
    'home.fabric.flameretardant.desc': 'Advanced flame retardant technology, meets EN11612 standard',
    'home.fabric.threeproof': 'Three-Proof Fabric',
    'home.fabric.threeproof.desc': 'Waterproof, oil-proof and stain-proof 3-in-1',
    'home.fabric.acidalkali': 'Acid & Alkali Resistant Fabric',
    'home.fabric.acidalkali.desc': 'Professional chemical corrosion resistant fabric',
    'home.fabric.antistatic': 'Antistatic Fabric',
    'home.fabric.antistatic.desc': 'Permanent antistatic treatment',
    'home.fabric.medical': 'Medical Fabric',
    'home.fabric.medical.desc': 'Antibacterial and fluid resistant',
    'home.fabric.polycotton': 'Poly-cotton Fabric',
    'home.fabric.polycotton.desc': 'Poly-cotton blend, cost-effective',
    'home.fabric.elastic': 'Elastic Fabric',
    'home.fabric.elastic.desc': 'High elasticity with good recovery',
    'home.fabric.fluorescent': 'Fluorescent Fabric',
    'home.fabric.fluorescent.desc': 'High visibility safety warning',
    'home.fabric.printed': 'Printed Fabric',
    'home.fabric.printed.desc': 'Clear patterns with vibrant colors',
    'home.fabric.linen': 'Linen Fabric',
    'home.fabric.linen.desc': 'Natural fiber, moisture absorbing and breathable',
    'home.fabric.wool': 'Wool Fabric',
    'home.fabric.wool.desc': 'Excellent warmth with soft hand feel',
    'home.news.1.title': 'Tianrui Textile Participates in 2024 China International Textile Fabric Expo',
    'home.news.1.summary': 'Showcasing latest functional fabric products',
    'home.news.2.title': 'Company Receives Provincial High-Tech Enterprise Recognition',
    'home.news.2.summary': 'Technical innovation capability recognized',
    'home.news.3.title': 'New Eco-Friendly Waterproof Fabric Successfully Developed',
    'home.news.3.summary': 'Using biodegradable materials, environmentally friendly',
    'about.intro': '13 Years Focus on Functional Fabrics',
    'about.profileTitle': 'Company Profile',
    'about.companyDesc': 'Founded in 2013, Xinxiang Tianrui Textile Printing & Dyeing Co., Ltd. specializes in producing workwear fabrics, uniform fabrics and functional fabrics. After 10 years of development, the company completed its transformation into a full-chain fabric supplier integrating spinning, weaving, dyeing and finishing in 2022. The company has 110,000 spinning spindles, 416 air-jet looms, 4 dyeing lines and 1 printing line. Products cover TC, CVC, cotton, TR, polyester, cotton-nylon, etc. Functional fabrics include flame retardant, oil and water resistant, anti-static, acid and alkali resistant, easy care, Teflon, UV protection, radiation protection, etc., covering firefighting, petroleum, chemical and other industries. The company has passed ISO9001, ISO14001 management system certifications, OEKO-TEX 100 certification, GRS certification, OCS certification, UL certification, and products can be tested by SGS, BTTG, ITS and other third-party testing institutions. The company has an experienced team with 4 expert-level chief engineers and 10 technical personnel with over 30 years of relevant field experience.',
    'about.companyPhilosophy': 'We adhere to "Quality First, Customer Supreme" philosophy, committed to providing the best products and services.',
    'about.yearsExp': 'Years of Industry Experience',
    'about.exportCountries': 'Export Countries',
    'about.globalClients': 'Global Clients',
    'about.patents': 'Patented Technologies',
    'about.milestones': 'Development History',
    'about.culture': 'Corporate Culture',
    'about.team': 'Core Team',
    'about.readMore': 'Read More',
    'about.milestone.2013': 'Company Founded',
    'about.milestone.2014': 'ISO9001 Certified',
    'about.milestone.2018': 'Exported to 100+ Countries',
    'about.milestone.2020': 'New Factory Launched',
    'about.milestone.2026': 'Industry Leader',
    'about.value.innovation': 'Innovation',
    'about.value.innovation.desc': 'Continuous R&D',
    'about.value.quality': 'Quality',
    'about.value.quality.desc': 'Strict Quality Control',
    'about.value.integrity': 'Integrity',
    'about.value.integrity.desc': 'Sincere Service',
    'about.value.winwin': 'Win-Win',
    'about.value.winwin.desc': 'Create Future Together',
    'about.team.founder': 'Founder/CEO',
    'about.team.founder.en': 'Founder/CEO',
    'about.team.cto': 'CTO',
    'about.team.cto.en': 'CTO',
    'about.team.sales': 'Sales Director',
    'about.team.sales.en': 'Sales Director',
    'about.team.production': 'Production Director',
    'about.team.production.en': 'Production Director',
    'honors.subtitle': 'Tianrui Textile always adheres to quality first, obtaining multiple international authoritative certifications and honors',
    'honors.iso9001': 'ISO 9001 Quality Management System',
    'honors.iso14001': 'ISO 14001 Environmental Management System',
    'honors.oekotex': 'OEKO-TEX Standard 100',
    'honors.hightech': 'National High-Tech Enterprise',
    'honors.ce': 'EU CE Certification',
    'honors.ul': 'US UL Certification',
    'honors.textileaward': 'China Textile Industry Technology Progress Award',
    'honors.famoustrademark': 'Jiangsu Famous Trademark',
    'factory.equipment': 'Production Equipment',
    'factory.productionLines': 'Production Lines',
    'factory.intelligentLine': 'Intelligent Production Line',
    'factory.environment': 'Environment Display',
    'contact.info': 'Contact Information',
    'contact.address': 'Address',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.workingHours': 'Working Hours',
    'contact.quickContact': 'Quick Contact',
    'contact.workTime': 'Mon-Fri 8:30-17:30',
    'inquiry.selectProduct': 'Please select a product',
    'inquiry.productPlaceholder': 'Enter product name (e.g., Flame Retardant Fabric, Waterproof Fabric)',
    'inquiry.quantityPlaceholder': 'e.g. 1000 meters',
    'inquiry.submitted': 'Inquiry submitted successfully!',
    'productDetail.notFound': 'Product not found',
    'productDetail.backToProducts': 'Back to Products',
    'productDetail.specs': 'Product Specifications',
    'productDetail.relatedProducts': 'Related Products',
    'productDetail.flameRetardant': 'Flame Retardant',
    'news.readMore': 'Read More',
    'advantages.title': 'Core Advantages',
    'advantages.iso': 'ISO Certified',
    'advantages.sample': 'Fast Sampling',
    'advantages.experience': '20 Years Experience',
    'advantages.global': 'Global Certifications',
    'products.title': 'Product Series',
    'products.subtitle': '11 categories of professional functional fabrics by material type, meeting various industry needs',
    'products.viewDetails': 'View Details',
    'products.inquiryNow': 'Inquire Now',
    'products.download': 'Download Sample',
    'products.productCount': 'Products',
    'products.features': 'Features',
    'products.specifications': 'Specifications',
    'products.applications': 'Applications',
    'factory.title': 'Factory Strength',
    'factory.subtitle': 'Advanced Production Equipment & Strict Quality Management',
    'news.title': 'Latest News',
    'partners.title': 'Partners',
    'footer.address': 'Address: Suzhou Industrial Park, Jiangsu, China',
    'footer.phone': 'Tel: +86 512-8888-8888',
    'footer.email': 'Email: info@tianrui-textile.com',
    'inquiry.title': 'Inquiry System',
    'inquiry.name': 'Your Name',
    'inquiry.company': 'Company Name',
    'inquiry.email': 'Email',
    'inquiry.phone': 'Phone',
    'inquiry.product': 'Product of Interest',
    'inquiry.quantity': 'Estimated Quantity',
    'inquiry.message': 'Message',
    'inquiry.submit': 'Submit Inquiry',
    'inquiry.submitting': 'Submitting...',
    'message.submitted': 'Message submitted successfully! We will contact you soon.',
    'message.submitting': 'Submitting...',
    'message.error.nameRequired': 'Please enter your name',
    'message.error.emailRequired': 'Please enter your email',
    'message.error.emailInvalid': 'Invalid email format',
    'message.error.messageRequired': 'Please enter your message',
    'message.placeholder.name': 'Enter your name',
    'message.placeholder.company': 'Enter company name',
    'message.placeholder.email': 'Enter your email',
    'message.placeholder.phone': 'Enter your phone number',
    'message.placeholder.message': 'Enter your message',
    'factory.capacity': 'Annual capacity: 50 million meters',
    'factory.automation': 'Automation rate: 95%',
    'factory.passRate': 'Pass rate: 99.5%',
    'chat.title': 'Online Support',
    'chat.placeholder': 'Type your question...',
    'chat.send': 'Send',
    // VideoHero
    'videoHero.brandTag': 'Tianrui Textile · Professional Protective Fabrics',
    'videoHero.mainTitle': '[Tianrui] Weaving the Future',
    'videoHero.subtitle': 'Weaving the Future',
    'videoHero.description': 'Focusing on R&D and production of functional fabrics, providing high-quality textile solutions for global customers',
    'videoHero.cta.products': 'Explore Products',
    'videoHero.cta.factory': 'Learn About Factory',
    'videoHero.companyName': 'Tianrui Textile',
    // DynamicBanner
    'dynamicBanner.brandTag': 'Tianrui Textile · Professional Protective Fabrics',
    'dynamicBanner.paramsLabel': 'Protection Performance Parameters',
    'dynamicBanner.cta.learnMore': 'Learn More',
    'dynamicBanner.scene.firefighter.title': 'Firefighting Uniforms',
    'dynamicBanner.scene.firefighter.subtitle': 'Flame Retardant & Heat Resistant · Protecting Lives',
    'dynamicBanner.scene.firefighter.desc': 'Using aramid fiber and flame retardant finishing technology, with excellent flame retardant and thermal protection performance, providing comprehensive safety protection for firefighters',
    'dynamicBanner.scene.oil.title': 'Oil Industry Uniforms',
    'dynamicBanner.scene.oil.subtitle': 'Anti-static & Flame Retardant · Industrial Safety First Choice',
    'dynamicBanner.scene.oil.desc': 'Designed for oil and gas industry, combining anti-static, flame retardant, and oil-resistant functions, adapting to harsh environments of offshore platforms and land-based oil fields',
    'dynamicBanner.scene.chemical.title': 'Chemical Industry Uniforms',
    'dynamicBanner.scene.chemical.subtitle': 'Acid & Alkali Resistant · Professional Chemical Protection',
    'dynamicBanner.scene.chemical.desc': 'Using multi-layer composite protection technology, effectively blocking various chemical liquid penetration, providing reliable chemical protection barrier for chemical production personnel',
    'dynamicBanner.scene.medical.title': 'Medical Uniforms',
    'dynamicBanner.scene.medical.subtitle': 'Antibacterial & Fluid Resistant · Medical Grade Protection',
    'dynamicBanner.scene.medical.desc': 'Medical-grade functional fabric with antibacterial, fluid resistant, and breathable comfort properties, meeting professional protection needs of operating rooms and wards',
    // FactoryShowcase
    'factoryShowcase.sectionTitle': 'Factory Tour',
    'factoryShowcase.sectionSubtitle': 'Modern intelligent factory with full industrial chain from spinning to dyeing',
    'factoryShowcase.scene.panorama.title': 'Factory Panorama',
    'factoryShowcase.scene.panorama.titleEn': 'Factory Panorama',
    'factoryShowcase.scene.panorama.desc': 'Modern industrial park integrating R&D, production, and warehousing',
    'factoryShowcase.scene.weaving.title': 'Weaving Workshop',
    'factoryShowcase.scene.weaving.titleEn': 'Weaving Workshop',
    'factoryShowcase.scene.weaving.desc': 'International advanced air-jet looms, efficiently weaving various functional fabrics',
    'factoryShowcase.scene.spinning.title': 'Spinning Mill',
    'factoryShowcase.scene.spinning.titleEn': 'Spinning Mill',
    'factoryShowcase.scene.spinning.desc': 'Intelligent spinning production line, controlling yarn quality from the source',
    'factoryShowcase.scene.dyeing.title': 'Dyeing & Printing',
    'factoryShowcase.scene.dyeing.titleEn': 'Dyeing & Printing',
    'factoryShowcase.scene.dyeing.desc': 'Eco-friendly dyeing process with precise colors and excellent fastness',
    'factoryShowcase.stat.area': 'Land Area',
    'factoryShowcase.stat.buildingArea': 'Building Area',
    'factoryShowcase.stat.greenRate': 'Green Rate',
    'factoryShowcase.stat.looms': 'Air-jet Looms',
    'factoryShowcase.stat.capacity': 'Annual Capacity',
    'factoryShowcase.stat.automation': 'Automation Rate',
    'factoryShowcase.stat.spindles': 'Spinning Spindles',
    'factoryShowcase.stat.dailyOutput': 'Daily Output',
    'factoryShowcase.stat.varieties': 'Yarn Varieties',
    'factoryShowcase.stat.dyeingLines': 'Dyeing Lines',
    'factoryShowcase.stat.printingLines': 'Printing Lines',
    'factoryShowcase.stat.processingCapacity': 'Daily Processing',
    'factoryShowcase.footer.capacity': 'Annual capacity: 50 million meters',
    'factoryShowcase.footer.automation': 'Automation rate: 95%',
    'factoryShowcase.footer.passRate': 'Pass rate: 99.5%',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('language') as Language;
      if (saved === 'zh' || saved === 'en') return saved;
    }
    return 'zh';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
