-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 询盘表
CREATE TABLE IF NOT EXISTS public.inquiries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id TEXT,
  product_name TEXT,
  quantity TEXT,
  customer_name TEXT NOT NULL,
  company_name TEXT,
  email TEXT NOT NULL,
  phone TEXT,
  message TEXT,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 留言表
CREATE TABLE IF NOT EXISTS public.messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  company TEXT,
  email TEXT NOT NULL,
  phone TEXT,
  content TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 产品表
CREATE TABLE IF NOT EXISTS public.products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  name_en TEXT,
  category TEXT NOT NULL,
  description TEXT,
  description_en TEXT,
  image_url TEXT,
  specifications JSONB,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 新闻表
CREATE TABLE IF NOT EXISTS public.news (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  title_en TEXT,
  summary TEXT,
  summary_en TEXT,
  content TEXT,
  content_en TEXT,
  image_url TEXT,
  is_published BOOLEAN DEFAULT TRUE,
  published_at TIMESTAMP DEFAULT NOW(),
  created_at TIMESTAMP DEFAULT NOW()
);

-- 启用RLS
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

-- 创建策略：允许匿名用户提交询盘和留言
CREATE POLICY "允许匿名提交询盘" ON public.inquiries FOR INSERT WITH CHECK (true);
CREATE POLICY "允许匿名提交留言" ON public.messages FOR INSERT WITH CHECK (true);

-- 创建策略：允许匿名用户查看产品和新闻
CREATE POLICY "允许匿名查看产品" ON public.products FOR SELECT USING (is_active = true);
CREATE POLICY "允许匿名查看新闻" ON public.news FOR SELECT USING (is_published = true);

-- 创建策略：允许匿名用户查看自己的询盘（通过邮箱匹配）
CREATE POLICY "允许匿名查看自己的询盘" ON public.inquiries FOR SELECT USING (true);